services:
  - type: web
    name: flask-mongo-app
    env: python
    region: oregon  # or change to your nearest region
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: FLASK_ENV
        value: development
